/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirmwareRouteImport } from './routes/firmware'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as WiringRouteImport } from './routes/wiring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmwareRoute = FirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const WiringRoute = WiringRouteImport.update({
  id: '/wiring',
  path: '/wiring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/firmware': typeof FirmwareRoute
  '/hardware': typeof HardwareRoute
  '/wiring': typeof WiringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firmware': typeof FirmwareRoute
  '/hardware': typeof HardwareRoute
  '/wiring': typeof WiringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/firmware': typeof FirmwareRoute
  '/hardware': typeof HardwareRoute
  '/wiring': typeof WiringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/firmware' | '/hardware' | '/wiring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/firmware' | '/hardware' | '/wiring'
  id: '__root__' | '/' | '/firmware' | '/hardware' | '/wiring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirmwareRoute: typeof FirmwareRoute
  HardwareRoute: typeof HardwareRoute
  WiringRoute: typeof WiringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmware': {
      id: '/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof FirmwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiring': {
      id: '/wiring'
      path: '/wiring'
      fullPath: '/wiring'
      preLoaderRoute: typeof WiringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirmwareRoute: FirmwareRoute,
  HardwareRoute: HardwareRoute,
  WiringRoute: WiringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
